language: node_js
node_js:
- '8.4'
notifications:
  slack:
    secure: RsLimn5QwEPDO+ZY97//M5CF7+xAA+QpMb1zj9jx560zEBgYpoT9bcqiFmUuQPWSKmyg9F2xd7RrcV9UMpMvaWhZ+FNZhIiu5432DftfL+wtZJsrVt38/2AvV9NRSecLRfeHmeIiVvxkpVOh+vqroqnzmRqTuI1WtyOghCh22Q6pkC5WkLQbTdK0MnVU0YQ8P3RbdmqJtsEq4n1lH/6KUm2nQRGjS3q9U6wo8S8sX0YOypEo8uAUEc9hJxczfZm9SYwA5Qrc6GJUS+J2JMgwqK/2krQ530v82zJjENjCq+/1muU6IzL71hNjmKbTS+wcLb4OdAdTxVh2v+hNZZIHYIZ7yYjfPa4hJzjNV3K7aNzGQ685YUlFkIMXZuvKNgKtZB9kma05KGxl53ldvjA4g3TiKKqWtmxA4CFhygnLeyBXQ3woHOfFUHzj4y7+ohtVLrE8agjyUyKScsIT1NEqRQQ9lS+qlV4fpz0oYZS7Q4IOvdLRuKHIyn3FLzAcDQAcJW17T1mkMoFHnOMI28NYbNxj/PUqwYEzX7rWoiMX/CM37Ju4owwMUEVU2ET8U5cIaUgyRoZUvPbL2cppKPA2Ppvdph0AXHkcbe7876i5JrG2i4JRhc0SMytZ/9gpOJyZj8BovWomkwxnU0vtEFNCNZoc3429az1sprTCKFhOVn0=
  on_success: change
  on_failure: always